language: ruby
sudo: false
rvm:
- 2.2.2
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
